### ISSUE TITLE
[🇪🇸] Cambiar el requerimiento de permisos para el actor en el combate automatizado

### ISSUE THREAD

**Issue by Lui-Sin** [AnimaBeyondDevelop/AnimaBeyondFoundry#101]
### Información

- **Versión de Foundry: X.X.X**
- **Versión del sistema: Sí**
- **Navegador: Desktop**
- **Tipo de sugerencia: Mejora**

### Descripción

El combate automatizado requiere que un jugador sea dueño de la ficha de su personaje y además que la tenga seleccionada como "perfil" al entrar en la partida. Esto limita enormemente el uso del combate automatizado con personajes que, por ejemplo, tengan familiares o criaturas controladas ya que los ataques y defensas solo puede realizarlas el GM, resultando en una mecánica muy tediosa.

Deberíamos mirar si se puede eliminar el requerimiento de que la ficha tenga que estar seleccionada como perfil para agilizar el combate y que el jugador no tenga que estar cambiando de perfil una o dos veces por turno de combate.

**Comment by Eryx5502** [comment]
Esto podría solucionarse cambiando la forma en que se obtiene el token cuando un usuario lanza el asistente de combate https://github.com/AnimaBeyondDevelop/AnimaBeyondFoundry/blob/40ef877d665651efc2cc300014483975a5c36586/src/module/combat/websocket/ws-combat/user/WSUserCombatManager.ts#L82

Tal cual está, coge el token del personaje que tienes seleccionado como "perfil". Sin embargo, cuando el máster es quien lanza el asistente se coge el token seleccionado. https://github.com/AnimaBeyondDevelop/AnimaBeyondFoundry/blob/40ef877d665651efc2cc300014483975a5c36586/src/module/combat/websocket/ws-combat/gm/WSGMCombatManager.ts#L127

Aún no conozco el código tanto, pero me parece que podría cambiarse sin problema para usar siempre el token seleccionado. ¿Se me escapa algo, @Linkaynn?

**Comment by Linkaynn** [comment]
@Eryx5502 

La razón por la que cogí el token que tenía asignado el jugador como perfil era debido a que es la unica forma que encontré para gestionar que X persona tiene permisos para "atacar" con Y fichas.

Foundry tiene un sistema para gestionar quien es _owner_ o tiene permisos para hacer ciertas cosas, pero no recuerdo que solucionara 100% el problema.

Aquí veo dos formas de atacar el problema:

- Ver si es posible con lo que ya nos da Foundry, discernir si un usuario tiene permisos "para atacar"
- Hacer un servicio custom que permita al GM decidir con qué fichas puede atacar cada usuario

Lo primero tiene el problema de que si Foundry cambia, nosotros tendremos que tocar eso, con el segundo punto, tardarémos más pero es más fiable ante actualizaciones.

Mi opinión es ir por la segunda opción.

**Comment by Eryx5502** [comment]
@Linkaynn

Entiendo lo que dices. Igual estoy siendo ingenuo, pero diría que podemos mantenernos con los permisos de foundry. Foundry sólo deja seleccionar tokens _owned_ por un usuario, y usa este mismo permiso para decidir qué jugador puede mover qué token. Sin haberlo pensado demasiado, mi impresión es que con los [permisos definidos por foundry](https://foundryvtt.com/article/actors/) debería ser suficiente:
 - Se daría _owner_ a los jugadores que puedan manejar al personaje (tanto mover su token como atacar con él).
 - Se daría _observer_ o _limited_ a los jugadores que pueden ver la ficha pero no pueden manejar el personaje.
 - Se daría _none_ a los jugadores que no pueden ver la ficha del pj ni tampoco manejarlo.

Si esta lógica fuese suficiente, la solución más sencilla sería cambiar lo que decía en mi mensaje anterior. ¿Se os ocurren escenarios en que este manejo de permisos no sea suficiente?

**Comment by Linkaynn** [comment]
@Eryx5502 

Si con _observer_ o _limited_ el usuario puede visualizar el token dentro de niebla de guerra, lo veo genial usar el _owner_ para este caso 👍🏻
