### ISSUE TITLE
[🇪🇸 - Bug] El cansancio se resta incorrectamente al usar el combate automatizado

### ISSUE THREAD

**Issue by Lui-Sin** [AnimaBeyondDevelop/AnimaBeyondFoundry#104]
### Información

- **Versión de Foundry: X.X.X**
- **Versión del sistema: X.X.X**
- **Navegador: Desktop**

### Descripción
Al gastar cansancio usando el combate automatizado, de forma aparentemente aleatoria se restan de forma adecuada o se restan dos veces.

**Comment by Eryx5502** [comment]
Estoy intentando mirar esto... Me ha costado un poco reproducirlo. Creo que se debe a que cuando se aprieta el botón de "mandar resultados al chat" se resta el cansancio por primera vez y cuando se aprieta "aplicar resutlados" se vuelve a restar.

No debería restarse nada al enviar el resultado al chat, pero no sé si este es todo el problema o sólo parte de él. Podéis poner exactamente los pasos que seguís para reproducir el error?
