### ISSUE TITLE
[🇪🇸 - Feature request] Escudos místicos y defensa a otros

### ISSUE THREAD

**Issue by Eryx5502** [AnimaBeyondDevelop/AnimaBeyondFoundry#108]
### Información

- **Versión de Foundry: 0.8**
- **Versión del sistema: 1.13**
- **Tipo de sugerencia: Nueva característica**

### Descripción

Añadir soporte al combate automatizado para defenderse con escudos místicos. Ahora mismo, existe la pestaña "místico" para defenderse cuando atacan a un personaje que tiene conjuros. Sin embargo, esto no permite proteger a otros con un escudo místico.

Dado que para proteger a otros con el escudo es necesario poner el escudo antes del ataque, se me ocurre registrar en la ficha los "escudos místicos" que tenga un personajes sobre sí mismo (lo que permitiría también llevar la cuenta de los puntos de vida que le queda al escudo). Éste tendría que guardar o bien referencia del mago que lo ha lanzado o bien su proyección para poder hacer las tiradas después. Si el escudo no para el ataque, se debe dar posibilidad de defensa al personaje atacado.

**Comment by Linkaynn** [comment]
Tal vez con añadir un elemento en la pantalla del defensor que indique que hay un escudo mágico también protegiendolo con los datos necesario para las tiradas valga para un primer soporte de este tipo en el combate automatizado. 

Creo que así reduciríamos el tiempo de desarrollo y a la vez daríamos soporte, con el tiempo lo iríamos mejorando. ¿Cómo lo ves?

**Comment by Eryx5502** [comment]
Es un poco más _tricky_, porque también está la posibilida de defenderse por uno mismo contra la misma tirada si el escudo falla (si no recuerdo mal). De todas formas, soporte básico tenemos justamente añadiendo un arma que represente el escudo, dándole los valores necesarios y usándola para hacer "parada", creo (no lo he probado).

**Comment by Linkaynn** [comment]
La idea sería permitir relanzar las tiradas del combate automatizado para así simular la primera defensa con escudo, y la segunda con esquiva/bloqueo en caso de que la primera falle

**Comment by Eryx5502** [comment]
Implementado en la versión v1.18.0
