### ISSUE TITLE
[🇪🇸 - Feature request] Permitir introducción de tiradas en el combate automatizado

### ISSUE THREAD

**Issue by Eryx5502** [AnimaBeyondDevelop/AnimaBeyondFoundry#109]
### Información

- **Versión de Foundry: 8**
- **Versión del sistema: 1.13**
- **Navegador: todos**
- **Tipo de sugerencia: Mejora**

### Descripción

Permitir introducir las tiradas en el asistente de combate, para poder cubrir tiradas especiales con valor predefinido o usarlo en mesa (donde se tirarían dados físicos y se introduciría la tirada).

**Comment by Linkaynn** [comment]
En el ataque como en la defensa, se podría añadir otra pestaña "Otros" para este tipo de casos en la que la tirada es fija

![image](https://user-images.githubusercontent.com/7486287/153767366-4656762b-6d5f-42d9-97cc-31b071dd74a2.png)
