### ISSUE TITLE
[🇪🇸 - Feature request] Añadir "otros" en ataque y defensa

### ISSUE THREAD

**Issue by Eryx5502** [AnimaBeyondDevelop/AnimaBeyondFoundry#110]
### Información

- **Versión de Foundry: 8**
- **Versión del sistema: 1.13**
- **Navegador: todos**
- **Tipo de sugerencia: Mejora**

### Descripción

Añadir una opción "otros" en el combate automatizado, tanto en el ataque como en la defensa. Esto haría aparecer campos para introducir los valores finales de las habilidades relevantes (h. ataque / h. defensa) y el daño y crítico en caso del ataque.

Esto sería útil para situaciones especiales que no encajen dentro de las distintas armas o situaciones "improvisadas".

**Comment by Linkaynn** [comment]
@Eryx5502 

¿En el caso del atacante no bastaría con crear un arma con los datos que se requiera?

**Comment by Eryx5502** [comment]
@Linkaynn 

En cualquier caso valdría, es cierto. Quizás no tenga tanto sentido esta issue, @DavidDPG dijo algo parecido cuando lo comenté en discord.

El motivo por el que la puse es que para algo situacional, que posiblemente no vas a repetir "nunca", crear un arma para atacar / defender con ella puede ser poco ágil. Además no es tan "directo" como si te saliese la opción en los diálogos. Tampoco tengo un razonamiento tan fuerte a favor, así que si vuestra impresión es que basta con el truquillo de añadir las armas, por mi está bien cerrar esta issue.

**Comment by Linkaynn** [comment]
@Eryx5502 

Si es algo ocasional, no sé si soportarlo sería lo adecuado. Si te parece bien podemos dejar esta tarea por aquí por si alguien quiere tomarla y dar un **aviso al navegante** de que tiene baja prioridad.
