### ISSUE TITLE
[🇪🇸 - Feature request] Agregar opción para cambiar el rango de crítico y de pifia

### ISSUE THREAD

**Issue by Linkaynn** [AnimaBeyondDevelop/AnimaBeyondFoundry#112]
Trasladada de la issue #92

**Comment by Linkaynn** [comment]
Para este caso tal vez podríamos usar la pestaña de configuración del personaje para añadir los campos necesarios

**Comment by JordiAlonsoLlovet** [comment]
Añadido un campo editable en la pestaña Configuración
![image](https://user-images.githubusercontent.com/38110017/166958994-a44c31af-ca51-4ef7-be4e-878ee75b0948.png)

**Comment by JordiAlonsoLlovet** [comment]
No se cual sería la traducción correcta en francés. Por ahora tengo puesto "Marge d'ouverte" y "Marge de Fumble"
