### ISSUE TITLE
[🇪🇸 - Feature request] Campo de descripción en hechizos y poderes mentales

### ISSUE THREAD

**Issue by Eryx5502** [AnimaBeyondDevelop/AnimaBeyondFoundry#113]
### Información

- **Versión de Foundry: 0.8**
- **Versión del sistema: 1.13**
- **Navegador: todos**
- **Tipo de sugerencia: Mejora**

### Descripción

Creo que lo comentamos en el discord, pero podría ser útil añadir a este tipo de items una descripción. Entiendo que no se incluyen las descripciones que aparecen en el libro por motivos de derechos. La intención de crear este campo no es distribuir dichas descripciones y por ello en el compendio se mantendrán en blanco. Sin embargo, creo que puede ser útil para los jugadores permitirles añadir sus propias descripciones y notas para que no tengan que estar consultando el libro (y para en el futuro dar opción a compartirlas fácilmente con el resto de jugadores a través del chat).

¿Qué os parece?

**Comment by Linkaynn** [comment]
![image](https://user-images.githubusercontent.com/7486287/156879933-1ff01dfd-c419-4e99-a1d6-cb5ced7221d2.png)

Meteríamos el campo de descripción bajo la zona de arcana, con la condición de que los items al colocarlos, se añadan de forma colapsada

**Comment by Linkaynn** [comment]
Para psíquicos lo mismo, debajo de las dificultades
