### ISSUE TITLE
[🇬🇧 - Bug] Error reported on the console, effects unclear

### ISSUE THREAD

**Issue by Eryx5502** [AnimaBeyondDevelop/AnimaBeyondFoundry#117]
### Information

- **Foundry version: 1.14.0**
- **System version: 0.8.9**
- **Browser: Firefox and Edge at least, but probably all**

### Description
![imagen](https://user-images.githubusercontent.com/32964371/161447238-c076e0c5-2216-468c-945f-8b798741af7a.png)
This error appears when changing the collapsed state for a spell (maybe also for other collapsable items.

#### Steps to reproduce

1. Open a sheet with spells on it.
2. Go to the Spells tab and change the collapsed state for one of the items.
3. Close the sheet.
The exception should appear on the console.

**Comment by Linkaynn** [comment]
Hi @Eryx5502 !

Thanks for the report.

I have just been trying to reproduce the issue following your steps and I didn't find the error in the console.

Have you more specific information? What kind of item were you collapsing? Was it at the same time that another user was using the sheet? 

https://user-images.githubusercontent.com/7486287/166101572-5d7e55ea-5688-4b6c-a32f-7d6f20ae690b.mp4

**Comment by Eryx5502** [comment]
This issue still happens but apparently the trigger is unclear and appears several times while operating with actor sheets, but I think it always reffers to this call
https://github.com/AnimaBeyondDevelop/AnimaBeyondFoundry/blob/be5b6051cc5c71ce04b5329c546480cd22f1b1d5/src/module/actor/ABFActor.ts#L116
It happens also after upgrading to the new version with Foundry 9. Effects are still unclear.

**Comment by Linkaynn** [comment]
Maybe we can assert if function exist in `items`. Some defensive code could be good
