### ISSUE TITLE
[🇪🇸 - Bug] El sistema no se actualiza correctamente

### ISSUE THREAD

**Issue by Lui-Sin** [AnimaBeyondDevelop/AnimaBeyondFoundry#133]
### Información

- **Versión de Foundry: 0.8.9**
- **Versión del sistema: 1.14.0**

### Descripción
Se produce un error al intentar actualizar el sistema de Anima en Foundry. Aparece en un recuadro el siguiente mensaje:
Required field 'entity' not present in PackageCompendiumData

#### Pasos de cómo reproducirlo
1. Ir a Sistemas
2. Click en Actualizar Anima Beyond Fantasy
...

#### Screenshots
![image](https://user-images.githubusercontent.com/80589418/169813041-ca79b33e-b7fe-4e1f-bd87-ee96d2bbd826.png)

**Comment by JordiAlonsoLlovet** [comment]
Pues intenta pasar una imagen del error con la consola abierta. Si estas en Desktop pulsa F12 y busca por ahí la pestaña Consola

**Comment by Lui-Sin** [comment]
No da error alguno en la consola, únicamente el mensaje que se ve en el mensaje, lo he reinstalado y al darle a actualizar sigue dando el mismo mensaje como respuesta.
