### ISSUE TITLE
[🇪🇸 - Feature request] Eliminar el campo Proyección Mágica

### ISSUE THREAD

**Issue by Lui-Sin** [AnimaBeyondDevelop/AnimaBeyondFoundry#142]
### Información

- **Versión de Foundry: X.X.X**
- **Versión del sistema: 1.15.1**
- **Navegador: Desktop|Chrome|Firefox|Safari...**
- **Tipo de sugerencia: Cambio**

### Descripción

Eliminar el campo Proy. Mágica pues es reiterativa en el combate con la Proy. Ofensiva y Defensiva cada una en su campo de acción (Ataques y defensas) para no tener que seleccionarlas cada vez en el combate automatizado.

**Comment by Eryx5502** [comment]
Se completó en la versión v1.18.0
