### ISSUE TITLE
[🇪🇸 - Bug] Error al calcular TAs superiores a 10.

### ISSUE THREAD

**Issue by JulenBordonaba** [AnimaBeyondDevelop/AnimaBeyondFoundry#148]
### Información

- **Versión de Foundry: 9.269**
- **Versión del sistema: 1.15.1**
- **Navegador: Desktop**

#### ¿Qué ocurre?
Si el valor final de TAs al combinar más de una armadura es superior a 10 esta se calcula mal
#### ¿Qué debería ocurrir?
Se debería calcular de manera normal, se toma la más alta 
#### Pasos de cómo reproducirlo
Equipa una armadura con 10 en todas las TAs y otra con 3 en todas las TAs, el valor final será 8 en todas

####Contexto adicional
Al combinar 2 armaduras de TA 10 o superior se calcula correctamente

**Comment by Lui-Sin** [comment]
Tras algo de prueba y error creemos que el fallo podría estar en la forma en la que se elige la armadura la armadura principal, se comete error al elegir entre armaduras de TA 10 o superior y armaduras < 10.

**Comment by Lui-Sin** [comment]
Tras más pruebas creemos firmemente que el fallo se debe al orden alfabético tomado por la función mutateTotalArmor.ts

El método sort está ordenando el valor de las TAs alfabéticamente (por lo que, por ejemplo, 3 se considera superior a 10)
![Error code](https://user-images.githubusercontent.com/80589418/185746851-85ed6e97-6fa9-4105-853a-0263dafde8d2.png)

**Comment by Lui-Sin** [comment]
Las pruebas las llevó a cabo @JulenBordonaba, cree que está ordenando alfabéticamente los números en código ASCII y por ello lo ordena mal.

**Comment by Eryx5502** [comment]
He estado echándole un ojo y parece que efectivamente el problema es que se ordena mal porque [`.sort()` hace una suerte de ordenado alfabético y ordena "cifra a cifra" en vez de como si fueran números.](https://stackoverflow.com/questions/1063007/how-to-sort-an-array-of-integers-correctly) Por eso notamos el error con armaduras a partir de 10.

Una opción sencilla sería usar arrays tipados como sugieren en el enlace.

**Comment by Eryx5502** [comment]
@Lui-Sin, duda: qué ocurre di tienes un TA de 10 y otro de 1? Si se redondea hacia abajo, que es como está, se quedaría a 10 la TA final. Funciona así?

**Comment by Lui-Sin** [comment]
@Eryx5502, correcto, se cogería como base el 10 al ser   el TA más alto y se le sumaría el redondeo hacia abajo del resto de TAs dividido entre 2, dando como resultado TA 10.

**Comment by Eryx5502** [comment]
Entonces está arreglado. Mañana hago la PR.
