### ISSUE TITLE
[🇬🇧 - Bug] Weapon and Armor Items not using ABF Item Sheet

### ISSUE THREAD

**Issue by mrianmerry** [AnimaBeyondDevelop/AnimaBeyondFoundry#149]
### Information

- **Foundry version: 9 Build 269**
- **System version: 1.15.1**
- **Browser: Chrome**

#### Behaviour
When adding armour and weapons, the items are uneditable and appear to use the default Foundry ItemSheet. GM can't switch them to the ABFItemSheet, and as such the stats for weapons and armours can't be included in the sheet. _(They default to 0 AT, 0+STR Damage, and 0 Initiative)_.

#### Expected behaviour
Items use the ABFItemSheet so they can be configured.

#### Screenshots
<details>
<summary>Weapon Item</summary>
<img width="529" alt="Screenshot 2022-08-20 at 23 29 52" src="https://user-images.githubusercontent.com/25342733/185768417-71df1553-776e-47b5-94e8-e836810884a3.png">
</details>
<details>
<summary>Armor Item</summary>
<img width="597" alt="Screenshot 2022-08-20 at 23 30 06" src="https://user-images.githubusercontent.com/25342733/185768420-11b614ed-08af-4cbd-97c7-a80dc64d05d7.png">
</details>

**Comment by mrianmerry** [comment]
Heya.
It's not every time - I was able to get the right info into the fields last night, but checking the game now the sheets have reverted back to the reported error state.
Reloading the tabletop doesn't really appear to solve anything, but as I'm not the GM I can't comment on the effects of restarting the server, sorry.

**Comment by Eryx5502** [comment]
That's funny... Has anything changed on your setting between now that you have the faulty behaviour and last night when it worked? Since you didn't mention, I assume it is always the same computer and that Chrome is updated.

Are you familiar with the Developer Tools in Chrome (F12 or to open). Could you check for any error in the console next time you notice the error?

**Comment by mrianmerry** [comment]
GM hasn’t changed any settings or info, so nothing wonky there. I’ll have a scope through the console output in a moment

**Comment by mrianmerry** [comment]
No error output in the console, which is a bit depressing.

**Comment by Eryx5502** [comment]
Uhm... I'd like to chase this one down, but I'm somehow lost here. Let's try to find some triggers next time it happens. I will also pay attention to see if it happens to me again, though it's been a while since last time.

Please report any odd thing you find!

@Linkaynn, any idea how to narrow it down?

**Comment by Linkaynn** [comment]
@Eryx5502 

I have seen this error before. I spent a lot of time debugging `foundry.js` core code and I saw that when our system request the template, Foundry responded with the default template.

This is even worse, some people in same campaign, can see it right and other wrong.

Is still happening @mrianmerry ?

**Comment by mrianmerry** [comment]
Yeah I just checked it now, actually, before I saw your message. Still happening, and still nothing in the console about any sort of error.

**Comment by Esteban-DA-COSTA** [comment]
Hello, I have the same issue but for the ki technic (I assume is used for ki because in french its write "technique")
I use the lastest stable version of FVTT directly from the FVTT software or Edge Windows 11

**Comment by Eryx5502** [comment]
Hi @Esteban-DA-COSTA. As of now, the supported version of FVTT is 9.280, although we plan to move into v10 as soon as possible.

However, the issue you're referring to now is unrelated with the version compatibility and also with the original issue reported by @mrianmerry. We are still working on the implementation of ki-related stuff, and there is yet no "standalone" item sheet for ki techniques.

**Comment by Eryx5502** [comment]
Can you please check if this issue is still a thing with the newer versions of Foundry and our system?

**Comment by mrianmerry** [comment]
Will do! I’ll let you know in the next week - not 100% sure when I’ll be able to check, but should be by then.

**Comment by Eryx5502** [comment]
I'm assuming this should be solved now, so I'm closing the issue. Do reopen if it persists.
