### ISSUE TITLE
[🇪🇸 - Bug] Se borra el contenido de los conjuros personalizados al añadir un nuevo conjuro personalizado

### ISSUE THREAD

**Issue by Ryuoniak** [AnimaBeyondDevelop/AnimaBeyondFoundry#152]
### Información

- **Versión de Foundry: 9 Build 280**
- **Versión del sistema: 1.15.1**

### Descripción 
Los hechizos personalizados borran su contenido al añadir otro hechizo personalizado

#### Pasos de cómo reproducirlo

1. Ir a ficha del personaje
2. Click en la pestaña de "Místico"
3. Cick en la subpestaña "Conjuros"
4. Click en añadir conjuros.
5. Rellenar conjuro.
6. Añadir nuevo conjuro.

**Comment by Eryx5502** [comment]
No he podido reproducir este issue en la nueva versión (PR #162). En mi caso, al añadir un nuevo conjuro el anterior mantiene todos los datos. Quizás se haya solucionado con los cambios o estoy malinterpretando algo?

**Comment by Eryx5502** [comment]
Cierro el issue ya que, que sepamos, ha desaparecido con las últimas actualizaciones.
