### ISSUE TITLE
[🇬🇧 - Bug] Sheet tabs not working on Foundry v10

### ISSUE THREAD

**Issue by Esteban-DA-COSTA** [AnimaBeyondDevelop/AnimaBeyondFoundry#153]
### Information

- **Foundry version: Version 10 build 288**
- **System version: 1.15.1**
- **Browser: Native software + edge Windows11**

### Description
Unable to have other tabs for actor.

#### Behaviour
When clicking on the last tab
![image](https://user-images.githubusercontent.com/41865716/198257338-82927425-60f1-47ab-9305-ffec87dc48a5.png)
and after on a tab to display, the checkbok unselect itself but the tab is displayed.
![image](https://user-images.githubusercontent.com/41865716/198257640-f15d2117-1601-4346-b292-cb29516c4a52.png)
But, when I register a date into the tab, for example Base accumulation, the tab close and I need to check the magic tab again. (information set are saved)
![image](https://user-images.githubusercontent.com/41865716/198258138-9d100e3a-ef08-459b-9d46-e7c7ea2a421e.png)

Finally, if I click again on a tab checkbox, it is selected but closing and going back into the character sheet unselect it again.
![image](https://user-images.githubusercontent.com/41865716/198258524-30c0c58d-1a97-4ae1-bc5d-981331ec12f2.png)

**Comment by Esteban-DA-COSTA** [comment]
I created the issue but I'm a junior developper so maybe I can try to solve it by myself if you're too busy with other development

**Comment by Eryx5502** [comment]
Hi there!

Thanks for reporting!

I think this issue is related with Foundry version 10, since we still not support it (support at the moment is restricted to v9.280). Probably some of the changes introduced on v10 broke the show/hide functionality.

Finally, if you're willing to collaborate you'd be more than welcome. We have a limited amount of resources right now so help is appreciated. We do have a discord channel to coordinate the development, if you're interested to join, please let us know!

**Comment by Esteban-DA-COSTA** [comment]
Yeah sure, just let me know how I can join the discord ;)

**Comment by Eryx5502** [comment]
So here you have: https://discord.gg/eHFGkXfS

We have a channel on the Spanish ABF's server. Once you join, one of the moderators will give you the correct role for the channel.

**Comment by Ghost49X** [comment]
Is there any  update on this issue?

**Comment by Eryx5502** [comment]
We still don't support Foundry v10. This and other issues should be solved once we release a new version supporting Foundry v10, but it might still take some time.

**Comment by ldmanfred** [comment]
Is there any update on this issue?

**Comment by Eryx5502** [comment]
We are still not supporting Foundry 10. Upgrading support to v10 is one of our immediate goals, but we have dependencies which still doesn't support it. Once we get there, we'll publish another version, but on the meantime we recommend sticking around with Foundry 9.

**Comment by Eryx5502** [comment]
Finally, versions of the system supporting Foundry v10 and v11 have been released! 🥳

I'm closing this issue since this bug should be fixed on those versions.
