### ISSUE TITLE
[🇪🇸 - Bug]  Disciplinas Psíquicas no pueden ser editas en la ficha.

### ISSUE THREAD

**Issue by Ryuoniak** [AnimaBeyondDevelop/AnimaBeyondFoundry#170]
### Información

- **Versión de Foundry: 11.307**
- **Versión del sistema: 1.15.1**
- **Navegador: Desktop|Chrome|Firefox|Safari...**

### Descripción

Aunque puedes crear Disciplinas Psíquicas sin ningún problema desde la ficha de personaje, luego no pueden ser editas.
Puedes escribir lo que quieres editar pero luego al cerrar y al volver a abrir lo que has cambiado ha desaparecido.

**Comment by Eryx5502** [comment]
Esta debería estar arreglada con https://github.com/AnimaBeyondDevelop/AnimaBeyondFoundry/commit/cf8e34bb94303a3e031fd233b465e0b2556b4a59, así que se cerrará con la PR #166.
