### ISSUE TITLE
[🇪🇸 - Bug] El rango de pifia se toma 0 por defecto, desactivando todas las pifias si no se cambia manualmente

### ISSUE THREAD

**Issue by Ryuoniak** [AnimaBeyondDevelop/AnimaBeyondFoundry#172]
Información

    Versión de Foundry: 11.307
    Versión del sistema: 1.15.1
    Navegador: Desktop|Chrome|Firefox|Safari...

Descripción

Abro sugerencia para aplicar la fórmula de pifia al turno. La pifia en el turno funciona algo diferente, en vez de tirar el dado se resta dependiendo de la pifia un penalizador:

Pifia de 1 (Penalizador de -125 a la tirada) 
Pifia de 2 (Penalizador de -100 a la tirada) 
Pifia de 3 (Penalizador de -75 a la tirada).

**Comment by Lui-Sin** [comment]
Adicionalmente, recordar que mediante estos penalizadores es posible obtener un resultado final de turno negativo.

**Comment by Eryx5502** [comment]
Sólo por concretar aclarar: cuando decís que se pone un penalizador de 125 a la tirada cuando sacas un 1 en el dado, queréis decir que el turno total es `iniciativa del pj - 125`, verdad?

**Comment by Lui-Sin** [comment]
Así es, sin sumar el 1 que haya obtenido del dado

**Comment by Eryx5502** [comment]
@Ryuoniak cómo haces la tirada? Haciendo click en `turno` en la ficha del personaje en cuestión?

Efectivamente, lanzando desde ahí no funciona, porque en lugar de coger el dado de la iniciativa está cogiendo un dado "genérico con abiertas y pifias". Sin embargo, desde el turn tracker sí funcionan las pifias en el turno correctamente!

**Comment by Eryx5502** [comment]
Vale! Creo que he visto lo que ocurría. El problema es que cuando no se especifica el rango de pifia en las opciones, el sistema lo está cogiendo como si fuese cero, y eso hace que justo cuando sacas un 3 en los dados no funcione. Sin embargo, debería funcionar si sacas un 1 o un 2. Lo arreglaré, pero como workaround hasta que lo tenga, podéis poner en las opciones (de todos los personajes (🙄) el rango de pifia igual a 3. Con eso sí funcionan los penalizadores creo.

**Comment by Ryuoniak** [comment]
Hice pruebas ayer y uno de los npcs sacó un 1 y no aplicó el penalizador. No puedo reproducirtelo ahora mismo por que me pillas fuera de casa pero cuando vuelva hago mas pruebas.

**Comment by Eryx5502** [comment]
@Ryuoniak Yo acabo de probarlo (sólo con el rango de pifia manualmente puesto a 3) y funciona tanto en el 1, en el 2 o en el 3.

Por otro lado, pregunta (también para @Lui-Sin que es casi siempre mi fuente de verdad en cuanto a normas): hay algún motivo por el que un pj podría tener rango de pifias = 0 (es decir, no puede pifiar)?

**Comment by Lui-Sin** [comment]
Sí, existe un poder de Elan de Barakiel que te quita todos los resultados de pifias.

**Comment by Ryuoniak** [comment]
He estado testeando y ni el resultado de 1 ni 2 e
![646362801035fd768ee5c85822d805e3](https://github.com/AnimaBeyondDevelop/AnimaBeyondFoundry/assets/113471527/f8d20f4c-b46f-43d4-80ee-5bfe4c7c1558)
![0f9df0edc758dec2889048d593c04c39](https://github.com/AnimaBeyondDevelop/AnimaBeyondFoundry/assets/113471527/bae127a3-5155-4bb7-b9f7-df79f23975e8)
n iniciativa aplica penalizador:
![f41bf071d052e8f2fc513b759bdcc175](https://github.com/AnimaBeyondDevelop/AnimaBeyondFoundry/assets/113471527/d6a04ce3-6201-44b3-8f0b-81d40082e4a6)
![6ac56509c69d959f1529ce676d76edb6](https://github.com/AnimaBeyondDevelop/AnimaBeyondFoundry/assets/113471527/21865736-a159-429d-bb19-ad5f8cacdf0c)

**Comment by Ryuoniak** [comment]
He cambiado el titulo de bug a petición. Pense que lo había cambiado pero quizas no se guardo.

**Comment by Ryuoniak** [comment]
Ah vale, a lo del titulo sin problema entonces, pensaba que no estaba aplicado xD.

He estado testeando y si pones el rango de pifia si que te hace las tiradas correctas, incluso con un rango de pifia de rango mas grande (He comprobado con un 50 de rango de pifia) aplica correctamente el penalizador de -75. El caso es que estaría bien que lo aplicara sin modificar el rango de pifia. En el caso de la tirada abierta no hace falta aplicar nada.

**Comment by Ryuoniak** [comment]
Añadiría que las tiradas normales como el combate o las secundarias tampoco aplican la pifia sin poner el rango de pifia en la ficha

**Comment by Eryx5502** [comment]
@Linkaynn, voy a necesitar un cable en esta.

El problema está en que se están sobrescribiendo sistemáticamente los valores por defecto de la configuración, tanto en `openOnDoubles`, `openRollRange` y `fumbleRange`. Esto es así por el fragmento de código a continuación:

https://github.com/AnimaBeyondDevelop/AnimaBeyondFoundry/blob/863f9493d8b6470fff9d108faaf4085890e4bf1c/src/module/rolls/ABFRoll.ts#L13-L23

`foundryRoll.data` tiene los valores de `actor.system` y por tanto `foundryRoll.data.general` está siempre definido (al inicializar un pj, si no se provee un valor distinto creo que foundry le mete directamente lo que hay en el `template.json`) y por lo tanto siempre entra en el `if` y sobrescribe los valores por defecto.

Además, al inicializar los datos del PJ con lo que hay en el `template.json`, el valor para `fumbleRange` es siempre 0, salvo que en las opciones del PJ se cambie manualmente. Esto hace que las pifias no aparezcan nunca, porque es como si el PJ no pudiese pifiar. 

No podemos resolverlo como se hace en el fragmento anterior para el OpenRollRange, porque según ha dicho @Lui-Sin en su respuesta más arriba puede ser legítimo poner un 0 en `fumbleRange` para algún personaje.

Sólo se me ocurre meter los valores por defecto en el `template.json` para que los nuevos actores tengan los valores buenos desde el principio, y hacer una migración de los datos para cambiar **todos** los actores que tengan 0 en el `fumbleRange` a el valor por defecto (es decir, 3) aunque no parece óptimo (si alguien tuviese el 0 adrede se lo estaríamos pisando).

Alguna idea mejor? Si no, voy a necesitar que me digas algo sobre cómo hacer migraciones porque no encuentro info al respecto.
