### ISSUE TITLE
[🇪🇸 - Bug] Error al mostrar las fichas en Foundry 11.308 por instalación del sistema corrompida

### ISSUE THREAD

**Issue by Restesia** [AnimaBeyondDevelop/AnimaBeyondFoundry#173]
### Información

- **Versión de Foundry: 1.308**
- **Versión del sistema: 1.15.1**
- **Navegador: Desktop|Chrome|Firefox|Safari... (En todos)**

### Descripción
Al migrar mi carpeta de DATA a una nueva instalación en Ubuntu todas las fichas aparecen rotas de la siguiente manera.

![image](https://github.com/AnimaBeyondDevelop/AnimaBeyondFoundry/assets/38212554/2e54725d-b5ec-4c00-a825-e4266552c8b9)

Esto es lo que aparece en la consola de desarrollo

![image](https://github.com/AnimaBeyondDevelop/AnimaBeyondFoundry/assets/38212554/2b633af2-201b-4c04-9fb4-f11f964db76b)

#### Pasos de cómo reproducirlo

1. Instalar Foundry en Ubuntu
2. Copiar la carpeta DATA en el lugar correspondiente
3. Abrir Foundry con normalidad

Es muy posible que los errores se deban a la forma en la que he traspasado tanto los sistemas como los mundos. Si necesitais saber algo más hacedmelo saber

**Comment by Eryx5502** [comment]
> **Versión de Foundry: 1.308**

Entiendo que eso es una errata y quieres decir versión 11.308?

En cualquier caso, no estoy pudiendo reproducir el error. He descargado y descomprimido la versión para linux/nodeJS de Foundry 11.308, y al lanzarla con una copia del data que yo tenía me abren las fichas sin problema.

Para ver qué ocurre, dime: La carpeta DATA que copias, es de una instalación anterior de Foundry v11? Si no, de qué versión es?

**Comment by Restesia** [comment]
Sí, es una errata, me refería a la versión 11.308.

La carpeta DATA es de una instalación de la v11. Te paso un link a la carpeta, la tengo en drive, es pesada, te lo aviso. 

https://drive.google.com/drive/folders/1lznsZnNI6UBuDhRikTGjB4nm7_y0YTkp?usp=drive_link

**Comment by Eryx5502** [comment]
Para intentar reproducirlo con tu mundo, pero sin tener que copiar toda la carpeta, dime cuál es el mundo que estás usando para descargarlo.

Por otro lado, para descartar que haya algún problema con módulos externos... Tienes otros módulos instalados? Puedes intentar desactivarlos todos y ver si también ocurre el error cuando no hay ningún módulo externo activado?

**Comment by Restesia** [comment]
El error sucede en todos los mundos. He desactivado todos los módulos y sigue dando el error.

**Comment by Eryx5502** [comment]
He estado haciendo algunas pruebas, y tus mundos (en realidad sólo he probado el de A&O) funcionan bien con mi instalación local, pero si uso tu instalación del sistema `animabf`, tanto en tu mundo como en los míos sale el error.

Por lo tanto, debe ser problema de la instalación como decías. Para arreglarlo, elimina el sistema `animabf` (borra la carpeta) e instálalo de nuevo.

PD: he visto que tienes archivos "basura" en la carpeta `Data/systems`, parecen de descomprimir el contenido del sistema `animabf` en la carpeta `Data/systems` en lugar de en `Data/systems/animabf`. Te recomendaría borrar todo lo que hay en esa carpeta excepto las carpetas de los sistemas que tienes instalados (`dnd5e`, `pf2e`, `animabf`) y el `README.txt`.

**Comment by Lui-Sin** [comment]
¿Podemos proceder a cerrar esta issue, @Eryx5502?

**Comment by Eryx5502** [comment]
Yo creo que sí. ¿@Restesia?
