### ISSUE TITLE
[🇪🇸] Añadir un tipo de defensa que se llame "Acumulación"

### ISSUE THREAD

**Issue by Linkaynn** [AnimaBeyondDevelop/AnimaBeyondFoundry#43]
*Esta issue ha sido trasladada desde el antiguo sistema de tareas*

Añadir un tipo de defensa que se llame "Acumulación", con la que el defensor no lance ningún dado, al ataque solo se le restará la absorción y las TAs del defensor

**Comment by Guote** [comment]
Otra diferencia entre defender con acumulación y normal es cuando el ser de acumulación defiende con sorpresa, que se divide a la mitad su absorción final (Absorción final = absroción base + TA = absorción base + (TA - reducción de TA del atacante)). 

Deberíamos añadir en caso de que se seleccione la defensa de tipo Acumulación un checkbox que diga "Has sido sorprendido?" o algo así. Creo que es mejor la checkbox que calcularlo automáticamente por si hay un pj con sangre de ouroboros, que cambia el rango de sorpresa, o porque hay otros efectos de sorpresa aparte de turno.

**Comment by JordiAlonsoLlovet** [comment]
Ya tengo la defensa por acumulación implementada, solo falta retocar los diálogos para que queden bonitos. Me gustaría que las dos checkbox de arriba ('Mostrar tirada' y 'Sin tirar dado') aparezcan en todas las pestañas excepto la de Acumulación, pero no encuentro la manera.
![DefenseDialog](https://user-images.githubusercontent.com/38110017/169276418-d2731e41-2e5b-4635-93cf-ea2e39f6a5b6.PNG)
![image](https://user-images.githubusercontent.com/38110017/169276487-fe029bc0-3a24-4ab8-996d-54e4a75cb4c4.png)
