### ISSUE TITLE
[🇪🇸 - Bug] Campos de escritura de la Proyección Psíquica

### ISSUE THREAD

**Issue by Lui-Sin** [AnimaBeyondDevelop/AnimaBeyondFoundry#56]
### Información

- **Versión de Foundry: 0.8.9**
- **Versión del sistema: 1.11.5**
- **Navegador: Desktop**

### Descripción
Se muestran los nombres de los atributos en inglés en vez de "Proyección Psíquica Ofensiva/Defensiva".

Adicionalmente, en el título pone Projecc. Psíquica, debería ser con "y" (Proyección)

#### Screenshots

![Fallo proyección psíquica](https://user-images.githubusercontent.com/80589418/134428683-dc3b0d15-896c-400d-9719-5567a22be921.png)

**Comment by Linkaynn** [comment]
@Lui-Sin 

Se va a revertir este cambio ya que la feat no estaba acabada
