### ISSUE TITLE
[🇪🇸 - Feature request] Siempre que se defienda un personaje, místico o psíquico

### ISSUE THREAD

**Issue by Linkaynn** [AnimaBeyondDevelop/AnimaBeyondFoundry#66]
### Descripción

Calcular el daño que realiza el ataque

**Comment by Eryx5502** [comment]
Es posible que este issue sea antiguo? Imagino que se dice por el daño que sufre el escudo, pero ese es el daño base del ataque y ya se muestra al GM en su diálogo de combate, no?
