### ISSUE TITLE
[🇪🇸] Actualizar el compendio de armas por la última versión que se subió

### ISSUE THREAD

**Issue by Lui-Sin** [AnimaBeyondDevelop/AnimaBeyondFoundry#79]
### Información

- **Tipo de sugerencia: Mejora**

### Descripción

El campo de daño del Scorpio está mal en el compendio de armas del sistema, ese error fue corregido en la siguiente versión del compendio pero no se ha actualizado en el sistema.

**Comment by Linkaynn** [comment]
Cierro esta issue por duplicada #88
