### ISSUE TITLE
[🇪🇸] Actualizar compendios de armas y magia

### ISSUE THREAD

**Issue by Linkaynn** [AnimaBeyondDevelop/AnimaBeyondFoundry#88]
### Descripción

Actualizar el compendio de magia y armas

#### Armas

https://cdn.discordapp.com/attachments/878970073065353216/885238693680525342/armas.db

#### Magia

https://cdn.discordapp.com/attachments/878970073065353216/891313850920603718/magia.db

**Comment by Eryx5502** [comment]
Creo que estoy pasando algo por alto. No es sólo copiar y pegar los archivos?

**Comment by Linkaynn** [comment]
Sí, con eso bastaría @Eryx5502

**Comment by Linkaynn** [comment]
Cierro la tarea por stale
