### ISSUE TITLE
Agregar opción para cambiar el rango de crítico y de pifia y activar o desactivar dobles. 

### ISSUE THREAD

**Issue by khadrus** [AnimaBeyondDevelop/AnimaBeyondFoundry#92]
Tal cual como en el título, aumentar o disminur los rangos de pifia y crítico para una ficha me resulta bastante util (más aun cuando es automático la explosión del dado).

Fuera de esto, los dobles son una mecanica en partidas con natura alta o que algunos masters dan a sus jugadores cuando llegan a cierto nivel de poder, añadir un boton que los habilite seria una mejora bastante considerable a los numeros de la ficha.

**Comment by Linkaynn** [comment]
@khadrus 

Sobre lo de cambiar el rango crítico y la pífia, totalmente de acuerdo. Hemos creado esta issue para llevarla a cabo: https://github.com/AnimaBeyondDevelop/AnimaBeyondFoundry/issues/112

Sobre la segunda parte tenemos que discutirlo mejor. Te decimos algo desde que tengamos más información.
