### ISSUE TITLE
[🇪🇸] Añadir daño y crítico manualmente al combate automatizado con magia y mentalismo

### ISSUE THREAD

**Issue by Lui-Sin** [AnimaBeyondDevelop/AnimaBeyondFoundry#93]
### Información

- **Versión de Foundry: X.X.X**
- **Versión del sistema: X.X.X**
- **Navegador: Desktop**
- **Tipo de sugerencia: Mejora**

### Descripción

Aprovechar el código ya hecho para el combate "físico" y crear un campo de daño inicializado a 0, el cual se pueda aumentar con un modificador, para que calcule el daño final con habilidades mágicas o psíquicas. También poder elegir en qué crítico dañan.

**Comment by Eryx5502** [comment]
No estoy seguro de entender este issue. No deberían obtenerse esos datos del conjuro y del grado en que se lanza?

**Comment by Eryx5502** [comment]
Ah, entiendo. Pero entonces es como un paso intermedio para solucionarlo a corto plazo? Lo suyo al final sería que los hechizos/poderes, dentro de la información que tienen por grado, también tengan el daño para que pueda extraerse automáticamente, o habéis pensado que es mejor evitar esto?

**Comment by Lui-Sin** [comment]
Sí, sería una solución a corto plazo, pero hay tantos hechizos (no todos de ataque) con daños tan diferentes... eso sin contar las metamagias que pueden alterar el daño.

**Comment by Linkaynn** [comment]
![image](https://user-images.githubusercontent.com/7486287/156880740-fe200e3b-ff10-4da3-9556-514b297aceed.png)

Añadir debajo un campo de Crítico y de Daño para el hechizo o el poder mental
